name = "Hotbuild Extra v1.0"
uid = "11111111-8dde-416a-9d76-aac3bb171b66"
version = 1.0
copyright = "by EntropyWins"
description = "Hotbuild for modded units and buildings. Mainly Blackops and Total Mayhem PDs"
author = "EntropyWins"
selectable = true
ui_only = true
url = "https://github.com/JeroenDeDauw/HotbuildExtra"
icon = "/mods/Hotbuild Extra/icon.png"